version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
  
